/* ----------------- General config -------------------------------- */
// Messages generated by the inputs
char *g_macro_messages[] = {
  "a",       // 1: letter "a"
  "b\n",     // 2: letter "b" then start a new line
  "Hi ",     // 3: word "Hi" then a space
  "there\n", // 4: word "there" then start a new line
  "5",       // 5: number "5"
  "6",       // 6: number "6"
  "warp",    // Special "mouse warp" command
  "For more info, see: https://www.superhouse.tv/moac \n"  // 8: Print a help message!
};

// Mouse warp locations. Any input can be defined as a "warp" button, which
// will cause the mouse cursor to jump to each of the coordinates in turn.
// Warp locations are X/Y values, starting at 0,0 in the top left corner of
// the screen and ending at 1000,1000 in the bottom right corner of the screen.
// Center of the screen is 500,500.
uint16_t warp_locations[][2] = { {250,250}, {500,250}, {500,500}, {750,750}, {980,980}, {10,970} };

/* Audible feedback */
#define ENABLE_BEEP      true            // Can also be controlled by a switch
#define BEEP_DURATION       2            // 100 Milliseconds
#define BEEP_TONE        2000            // Frequency in Hz

/* OLED display */
#define DISPLAY_TIMEOUT     5            // Seconds

/* ----------------- Hardware-specific config ---------------------- */
/* Button inputs */
uint8_t g_input_pin_list[8] = { A0, A1, A2, A3, A4, A5, A6, A7 };

/* Piezo buzzer */
#define PIEZO_PIN          11            // Audible output

/* OLED display */
#define OLED_RESET         -1            // No dedicated reset connection
