/* ----------------- General config -------------------------------- */
// Messages generated by the inputs
char *g_macro_messages[] = {
  "a",       // 1: letter "a"
  "b\n",     // 2: letter "b" then start a new line
  "Hello ",  // 3: word "Hello" then a space
  "there\n", // 4: word "there" then start a new line
  "5",       // 5: number "5"
  "6",       // 6: number "6"
  "7",       // 7: number "7"
  "8"        // 8: number "8"
};

/* Audible feedback */
#define ENABLE_BEEP      true            // Can also be controlled by a switch
#define BEEP_DURATION     100            // Milliseconds
#define BEEP_TONE        2000            // Frequency in Hz

/* OLED display */
#define DISPLAY_TIMEOUT     5            // Seconds

/* ----------------- Hardware-specific config ---------------------- */
/* Button inputs */
uint8_t g_input_pin_list[8] = { A0, A1, A2, A3, A4, A5, A6, A7 };

/* Piezo buzzer */
#define PIEZO_PIN          11            // Audible output

/* OLED display */
#define OLED_RESET         -1            // No dedicated reset connection
