/* ----------------- General config -------------------------------- */
// Messages generated by the inputs
char *g_macro_messages[] = {
  "a",       // 1: letter "a" on its own
  "b\n",     // 2: letter "b" then start a new line
  "Hello ",  // 3: word "Hello" then a space
  "there\n", // 4: word "there" then start a new line
  "5",       // 5: number "5" on its own
  "6",       // 6: number "6" on its own
  "7",       // 7: number "7" on its own
  "8"        // 8: number "8" on its own
};

// Audible feedback
#define     ENABLE_BEEP   true

// Display
#define     DISPLAY_TIMEOUT          5           // Seconds

/* ----------------- Hardware-specific config ---------------------- */
// OLED
#define     OLED_RESET               0            // Is this connected?

// Button inputs
uint8_t g_input_pin_list[8] = {A0,A1,A2,A3,A4,A5,A6,A7};
// MISTAKE HERE! I connected to A11 (D6) but it's the wrong pin. Should be A7. {A0,A1,A2,A3,A4,A5,6,11}

#define     PIEZO_PIN               11
